#Authored By GW KANG

name: WINDOWS TOOLS

on: 
  workflow_dispatch:
    inputs:
      name:
        description: 'Select Any Tool to Run'
        type: choice
        options:
        - Windows
        - FF_Ripper
        - Mixamo
        - Blender
        - Ripping_Tools
        - Unity
      authcode:
        description: 'Enter Powershell code from crd website' 
        required: true
  
jobs:
  build:
    name: Setting up ${{ inputs.name }}
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
    - name: Setting Up ${{ inputs.name }}
      run:  |
        # SETTING UP 
        & {Set-NetFirewallProfile -Profile Domain,Public,Private -Enabled False | Out-Null}
        Invoke-WebRequest -Uri 'https://codeload.github.com/indexkang/GWKANG-CGI-TOOLS/zip/refs/heads/main' -OutFile 'GWKANG-CGI-TOOLS-main.zip' | Out-Null
        7z x 'GWKANG-CGI-TOOLS-main.zip' | Out-Null
        cd GWKANG-CGI-TOOLS-main | Out-Null
        cd ${{ inputs.name }} | Out-Null
        ./installer.ps1 -s | Out-Null
        cd | Out-Null
        # STARTING CHROME REMOTE DESKTOP
        ${{ github.event.inputs.authcode }} -pin=654321
    - name: ${{ inputs.name }} Is Running!
      run: |
        # CONSOLE RUNNING
        $Env:COMPUTERNAME
        cd GWKANG-CGI-TOOLS-main 
        ./counter2.ps1 -Wait
        ./counter3.ps1 -Wait
